spring:
  application:
    name: "configserver"
  profiles:
    active: native
#    active: git
  cloud:
    config:
      server:
        search-locations: "file:///C:\\Users\\I16453834\\WS\\sangit\\sanapps\\v2\\configserver\\src\\main\\resources\\config"
        # native:
#        search-locations: "classpath:/config"

server:
  port: 8071
